spring.application.name=smartbusmng
server.port=8081

# =========================
# Session / Web
# =========================
server.servlet.session.timeout=30m
server.servlet.session.tracking-modes=cookie
server.servlet.session.persistent=false

spring.main.allow-bean-definition-overriding=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.sql.init.mode=never
spring.profiles.default=local

# =========================
# Encoding
# =========================
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

# =========================
# Paging
# =========================
custom.page-unit=10
custom.page-size=10

# =========================
# Project Meta
# =========================
project.name=smartbusmng
ad.entity.id=AD001
ma.entity.id=MA001

# =========================
# Thymeleaf
# =========================
spring.thymeleaf.prefix=classpath:/templates/thymeleaf/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# =========================
# Static Resources
# =========================
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

# =========================
# MyBatis
# =========================
mybatis.mapper-locations=classpath:/egovframework/mappers/*.xml
mybatis.type-alias-package=egovframework.smartbusmng.model


# =========================
# dispatch
# =========================
dispatch.batch-size=10
dispatch.fixed-delay-ms=1000
dispatch.stuck-sec=30
dispatch.retry-delay-sec=10
dispatch.max-retry=1

# =========================
# Logging
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG
logging.level.egovframework.smartbusmng.mapper=DEBUG
logging.level.egovframework.smartbusmng.mapper.FacilityMapper=TRACE